apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: youngchulshin/my-app:0.0.3
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /api/healthcheck
        port: 8080
      initialDelaySeconds: 10 # 10초 이후에 5초에 한번씩 요청한다. 3번 실패하면 비정상으로 판단
      periodSeconds: 5
      failureThreshold: 3
      timeoutSeconds: 3