apiVersion:  v1
kind: Pod
metadata:
  name: my-empty-dir
spec:
  containers:
  - name: content-creator
    image: alicek106/alpine-wget:latest
    args: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: my-empty-dir-volume
      mountPath: /data
  - name: apache-webserver
    image: httpd:2
    volumeMounts:
    - name: my-empty-dir-volume
      mountPath: /usr/local/apache2/htdocs/
  volumes:
  - name: my-empty-dir-volume
    emptyDir: {}