apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv01
spec:
  capacity: 
    storage: 1Gi
  storageClassName: my-storage
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath: # PV을 hostPath로 정의
    path: /pv-test/pv01