apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: youngchulshin/my-message:1.1.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: my-pvc
      mountPath: /storage
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: my-pvc01