apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: this-is-my-app
  template:
    metadata:
      labels:
        app: this-is-my-app
    spec:
      containers:
      - name: my-app
        image: youngchulshin/my-app:0.0.6
        ports:
        - containerPort: 8080
      # livenessProbe:
      #   httpGet:
      #     path: /api/healthcheck
      #     port: 8080
      #   initialDelaySeconds: 10
      #   periodSeconds: 5
      #   failureThreshold: 3
      #   timeoutSeconds: 3
      # readinessProbe:
      #   httpGet:
      #     path: /api/ready
      #     port: 8080
      #   initialDelaySeconds: 20
