apiVersion: v1
kind: Pod
metadata:
  name: my-prod-pod
spec:
  containers:
  - name: my-container
    image: youngchulshin/my-message:1.1.0
    ports:
    - containerPort: 8080
    env:
    - name: SPRING_PROFILES_ACTIVE
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: active_profile