apiVersion: v1
kind: Pod
metadata:
  name: my-prod-pod
spec:
  containers:
  - name: my-container
    image: youngchulshin/my-message:1.0.0
    ports:
    - containerPort: 8080
    args: ["--spring.profiles.active=prod"]